@baseUrl = http://localhost:3000
@authToken = {{auth.response.body.accessToken}}

@refreshToken = {{auth.response.body.refreshToken}}

#


# RECADOS

### Lista todos os recados
GET {{baseUrl}}/recados/

### Lista um recado específico
GET {{baseUrl}}/recados/2/

### Cria um novo recado
POST {{baseUrl}}/recados/
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "texto": "Recado 5",
    "paraId": 5
  }

### Atualiza um recado existente
PATCH {{baseUrl}}/recados/4/
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "texto": "Recado 32 alterado",
    "lido": true
  }

### Deleta um recado
DELETE {{baseUrl}}/recados/7/
Authorization: Bearer {{authToken}}


#


# PESSOAS

### Lista todas as pessoas
GET {{baseUrl}}/pessoas/
Authorization: Bearer {{authToken}}

### Lista uma pessoa específica
GET {{baseUrl}}/pessoas/2/
Authorization: Bearer {{authToken}}

### Cria uma nova pessoa
POST {{baseUrl}}/pessoas/
Content-Type: application/json

{
    "nome": "João",
    "email": "joao@example.com",
    "password": "senha123"
}

### Atualiza uma pessoa existente
PATCH {{baseUrl}}/pessoas/3/
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "nome": "Gabriel Souza",
    "password": "novaSenha123"
}

### Deleta uma pessoa
DELETE {{baseUrl}}/pessoas/4/
Authorization: Bearer {{authToken}}


#

# AUTHENTICATE

### Auth
# @name auth
POST {{baseUrl}}/auth/
Content-Type: application/json

{
    "email": "gabriel@example.com",
    "password": "novaSenha123"
}

### REFRESH AUTHENTICATE
# @name refreshAuth
POST {{baseUrl}}/auth/refresh
Content-Type: application/json

{
    "refreshToken": "{{refreshToken}}"
}


#

# UPLOAD

### Foto da pessoa
POST {{baseUrl}}/pessoas/upload-picture/
Authorization: Bearer {{authToken}}
Content-Type: multipart/form-data;boundary=----BoundaryDelimitadorHttp

------BoundaryDelimitadorHttp
Content-Disposition: form-data; name="file"; filename="sharingan2.png"
Content-Type: image/png

< ./dev/images/sharingan2.png
------BoundaryDelimitadorHttp--

### Ver foto
GET {{baseUrl}}/pictures/3.png