@baseUrl = http://localhost:3000
@authToken = {{auth.response.body.accessToken}}

#


# RECADOS

### Lista todos os recados
GET {{baseUrl}}/recados/

### Lista um recado específico
GET {{baseUrl}}/recados/2/

### Cria um novo recado
POST {{baseUrl}}/recados/
Content-Type: application/json

{
    "texto": "Recado 2",
    "de": "Manoel",
    "para": "Tereza"
  }

### Atualiza um recado existente
PATCH {{baseUrl}}/recados/2/
Content-Type: application/json

{
    "texto": "Recado 2 alterado",
    "de": "Rafael",
    "para": "Marina",
    "lido": true
  }

### Deleta um recado
DELETE {{baseUrl}}/recados/3/


#


# PESSOAS

### Lista todas as pessoas
GET {{baseUrl}}/pessoas/
Authorization: Bearer {{authToken}}

### Lista uma pessoa específica
GET {{baseUrl}}/pessoas/2/

### Cria uma nova pessoa
POST {{baseUrl}}/pessoas/
Content-Type: application/json

{
    "nome": "João",
    "email": "joao@example.com",
    "password": "senha123"
}

### Atualiza uma pessoa existente
PATCH {{baseUrl}}/pessoas/4/
Content-Type: application/json

{
    "nome": "João Silva",
    "password": "novaSenha123"
}

### Deleta uma pessoa
DELETE {{baseUrl}}/pessoas/2/


#

# AUTHENTICATE

### Auth
# @name auth
POST {{baseUrl}}/auth/
Content-Type: application/json

{
    "email": "gabriel@example.com",
    "password": "senha123"
}